config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:  '',
                     path_names: {:sign_in => 'login', :sign_out => 'logout'},
                     controllers: {registrations: 'users/registrations'}
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]

  
  get 'static_pages/about'

  get 'static_pages/contact'
  get 'static_pages/index'
  get 'static_pages/landing_page'
  post 'static_pages/thank_you'
  post 'payments/create'
  get 'payments/create'
  
  mount ActionCable.server => '/cable'

  root 'static_pages#landing_page'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end


# standard way, 
# because CRUD created actions in conrtoller(products)
# get '/products/:id', to: 'products#show'

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def create
    token = params[:stripeToken]
    @product = Product.find(params[:product_id])
    @user = current_user

    # This will charge the user's card:
    begin
      charge = Stripe::Charge.create(
        :amount => (@product.price * 100).to_i,
        :currency => "usd",
        :source => token,
        :description => params[:stripeEmail],
        :receipt_email => params[:stripeEmail]
      )
      if charge.paid
        Order.create(product_id: @product.id, user_id: @user.id,
      total: @product.price.to_i)
        UserMailer.order_placed(@user, @product).deliver_now
      end

    rescue Stripe::CardError => e
      # When the card has been declined
      body = e.json_body
      err = body[:error]
      flash[:error] = "Unfortunately, there was an error processing your payment: #{err[:message]}"
    end
   end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/create.html.erb
<body class="payment_page">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-xs-12 thankyou_note">
        <p class="product_title"> Thank you for your purchase!</p>
        <p class="create_text"> Be sure to leave us a <%=link_to 'comment', product_path(@product)%>. </p>
        <p class="create_text">  Browse through our other <%= link_to 'bikes!', products_path %> </p>
      </div>
    </div>
  </div>
</body>