config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:  '',
                     path_names: {:sign_in => 'login', :sign_out => 'logout'},
                     controllers: {registrations: 'users/registrations'}
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]

  
  get 'static_pages/about'

  get 'static_pages/contact'
  get 'static_pages/index'
  get 'static_pages/landing_page'
  post 'static_pages/thank_you'
  post 'payments/create'
  get 'payments/create'
  
  mount ActionCable.server => '/cable'

  root 'static_pages#landing_page'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end


# standard way, 
# because CRUD created actions in conrtoller(products)
# get '/products/:id', to: 'products#show'

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  validates :name, presence: true

  def self.search(search_term)
    like_operator = Rails.env.development? ? 'like' : 'ilike'
    Product.where("name #{like_operator} ?", "%#{search_term}%")
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.order(:rating)
  end

  def average_rating
    comments.average(:rating).to_f
  end

  def views
    $redis.get("product:#{id}")
  end

  def viewed!
    $redis.incr("product:#{id}")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    #if Rails.env.development?
      #byebug
    #end 
    @products = params[:q].present? ? Product.search(params[:q]) : Product.all
    @products = @products.paginate(:page => params[:page], :per_page=>6)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page =>5)
    @product.viewed!
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    logger.debug "Product: #{@product.name}"

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s,:number)
      "products/all-#{count}-#{max_updated_at}"
    end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group top_of_field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :image_url %>
      <%= f.text_field :image_url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :colour %>
      <%= f.text_field :colour, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control"%>
    </div>

    <div>
      <%= f.submit class: "btn btn-info" %>
    </div>
  <% end %>
  </div>
</div>
<br>
<br>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4> Add a review: </h4>
  <%= form_for([@product, @product.comments.build], remote:true) do |f| %>
    <p>
      <%= f.text_area :body, id:"comment_textarea" %>
    </p>
   
    <p>
      <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
<section class="col-md-6 col-lg-6 col-xs-12 product_section">
  <p class="product_title"><%= product.name %></p>
  <section class="product_image">
    <% if product.image_url.present? %>
      <%=link_to(image_tag(product.image_url, class:"product_image"), product) %>
    <% end %>
  </section>
  
  <p class="product_description"><%= product.description %></p>

  <p>Colour: <%= product.colour %></p>
  <p>Price: $<%= product.price %></p>
<% end %>
  <ul class="inline_list">
    <li><%= link_to 'Show', product %>|</li>
    <li><%= link_to 'Edit', edit_product_path(product) %>|</li>
    <li> <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
</section>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class:"show_links" %> |
<%= link_to 'Back', products_path, class:"show_links" %>

app/views/products/index.html.erb
<h1>Products</h1>
<section class="container-fluid">
  <% cache @products do %>
    <% @products.each do |product| %>
      <%= render partial: 'product', locals: {product: product } %>
    <% end %>
  <% end %>
</section>

  <%= will_paginate @products, :page_links =>true %>

 <br>

 <section id="new_product_link">
  <%= link_to 'New Product', new_product_path %>
</section>
  

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div id="new_listing">
  <p id="notice"><%= notice %></p>
</div>

<section class="container-fluid">
  <div class="row" data-product-id ="<%= @product.id%>">
    <div class="col-md-6 col-lg-6 col-xs-12 product_div">
      <p class="product_title"><%= @product.name %> </p>
      <section class="product_image"> 
        <% if @product.image_url.present? %>
          <%= image_tag(@product.image_url, class:"img-zoom",  data_zoom_image: "@product.image_url") %>
        <% end %>
      </section>
      <p class="product_description"> <%= @product.description %> 
      </p>
      <p> Colour: <%= @product.colour %></p>
      <p> Price: $<%= @product.price %> </p>
      <%= form_tag "/payments/create" do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: 'shared/stripe_checkout_button' %>
      <% end %>
      <p> Average Rating: <div class="rated" id="average-rating" data-score= "<%=@product.average_rating %>"></div></p>
      
      <%= link_to 'Edit', edit_product_path(@product), class:"show_links" %> |
      <%= link_to 'Back', :back, class:"show_links" %>

    </div>
    <div class="col-md-6 col-lg-6 col-xs-12 product_div">
      <h4 class="product_title"> <span class="glyphicon glyphicon-pencil"></span> Comments </h4>
      <div id="comments">
        <div class="alert alert-info" style="display: none" role="alert">
        A new comment was posted!</div>
        <%= render 'new_comment' %>
        <%= render 'comments' %>
      </div>
      <%= will_paginate @comments%>
      <h6 class="viewed"> Views:
        <span class="badge">
          <%= @product.views%>
        </span>
      </h6>
    </div>
  </div> 
</section>