config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path:  '',
                     path_names: {:sign_in => 'login', :sign_out => 'logout'},
                     controllers: {registrations: 'users/registrations'}
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]

  
  get 'static_pages/about'

  get 'static_pages/contact'
  get 'static_pages/index'
  get 'static_pages/landing_page'
  post 'static_pages/thank_you'
  post 'payments/create'
  get 'payments/create'
  
  mount ActionCable.server => '/cable'

  root 'static_pages#landing_page'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end


# standard way, 
# because CRUD created actions in conrtoller(products)
# get '/products/:id', to: 'products#show'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bike Berlin</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class ="navbar navbar-default">
      <div class="container-fluid">

      <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button"><span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>

        <ul class="nav navbar-nav">
          <li><%=link_to 'Home', root_path %></li>
        </ul>
        <nav class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" action="/products">
            <div class="form-group">  
            <%= form_tag("/products", method:"get") do %>
            <%= label_tag(:q, "") %>
            <%= text_field_tag(:q, nil, class: "form-control search_field", placeholder: "search") %>
            <%= submit_tag("Search", class: "btn btn-primary") %>
            </div>
          </form>
            <ul class="nav navbar-nav navbar-right dropdown-toggle">

            <li><%=link_to 'Bikes', products_path %></li>
            <li><%=link_to 'About', static_pages_about_path %></li>
            <li><%=link_to 'Contact', static_pages_contact_path %></li>

            <% if current_user && current_user.admin? %>
              <li><%=link_to 'Users', users_path %></li>
              <li><%=link_to  "My info", edit_user_path(current_user)%></li>
            <% elsif signed_in? %>
              <li><%=link_to  "My info", edit_user_path(current_user)%></li>
            <% else %>
              <li><%=link_to "Sign Up", new_user_registration_path%></li>
            <% end %>
            <% end %>
          
            <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
            </li>
          </ul>
        </nav>
      </div>
    </nav>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <% if notice %>
      <div class="alert alert-warning" role="notice">
        <%= notice %>
      </div>
      <% end %>
    <%= yield %>

    <footer class="container-fluid">
      <p>&copy; 2015 Bike Berlin</p>
    </footer>
  </body>
</html>